apiVersion: apps/v1
kind: Deployment
metadata:
  name: aas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aas
  template:
    metadata:
      labels:
        app: aas
    spec:
      containers:
        - name: aas
          image: oci.stackable.tech/sandbox/xfsc-aas@sha256:aaf86f2c5e450d3b699993c44dbb162b2e0265cf65104a76c6837b4d199c32d7
          ports:
            - name: web
              containerPort: 9000
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql-aas:5432/aas
            - name: SPRING_DATASOURCE_USERNAME
              value: aas
            - name: SPRING_DATASOURCE_PASSWORD
              value: aas
            - name: AAS_IAM_BASEURI
              value: http://key-server:8080
            - name: AAS_TSA_URL
              value: http://tsa:5000
            - name: AAS_OIDC_ISSUER
              value: http://auth-server:9000
            - name: AAS_CACHE_TTL
              value: 5m
            - name: LOGGING_LEVEL_EU_XFSC_AAS
              value: DEBUG
            - name: AAS_INVITATION_URI
              value: http://tsa:5000/requests?

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: aas
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    app: aas
