---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-iceberg
spec:
  image:
    productVersion: 3.1.3
  clusterConfig:
    database:
      connString: jdbc:postgresql://postgresql-hive-iceberg:5432/hive
      dbType: postgres
      credentialsSecret: postgres-hive-iceberg-credentials
    hdfs:
      configMap: hdfs
    authentication:
      kerberos:
        secretClass: kerberos
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-hive-iceberg-credentials
type: Opaque
stringData:
  username: hive
  password: hive
