
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: kerberos
spec:
  backend:
    kerberosKeytab:
      realmName: KNAB.COM
      kdc: krb5-kdc.default.svc.cluster.local
      admin:
        mit:
          kadminServer: krb5-kdc.default.svc.cluster.local
      adminKeytabSecret:
        namespace: default
        name: secret-operator-keytab
      adminPrincipal: stackable-secret-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-operator-keytab
data:
  # To create keytab. When prompted enter password asdf
  # cat | ktutil << 'EOF'
  # list
  # add_entry -password -p stackable-secret-operator@KNAB.COM -k 1 -e aes256-cts-hmac-sha384-192
  # wkt /tmp/keytab
  # EOF
  keytab: BQIAAABYAAEACEtOQUIuQ09NABlzdGFja2FibGUtc2VjcmV0LW9wZXJhdG9yAAAAAWXV95cBABQAIHGBpY8vMrSSouV3HaEn8V2GF676APUVjx3avUOQlz/GAAAAAQ==
