---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-import-dir
          configMap:
            name: keycloak-gaia-x-realm
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.3
          # Keycloak is running in development mode: https://www.keycloak.org/server/configuration#_starting_keycloak
          # production mode disables HTTP and requires a TLS configuration, which is currently very difficult to configure
          # given that we're running on a NodePort
          args: ["start-dev", "--import-realm", "--hostname-url=http://key-server:8080"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: admin
          volumeMounts:
            - name: keycloak-import-dir
              mountPath: /opt/keycloak/data/import
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: key-server
  labels:
    app: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
stringData:
  admin: "{{ keycloakAdminPassword }}"
