apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
stringData:
  superset: "{{ keycloakSupersetClientSecret }}"
  trino: "{{ keycloakTrinoClientSecret }}"
---
# This job creates users and clients in Keycloak.
# It also creates a ConfigMap with user IDs used by OPA
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-keycloak
spec:
  template:
    spec:
      containers:
      - name: setup-keycloak
        image: docker.stackable.tech/stackable/testing-tools:0.2.0-stackable0.0.0-dev # We need 0.0.0-dev, so we get kubectl
        env:
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-admin-credentials
                key: admin
          - name: SUPERSET_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-client-secrets
                key: superset
          - name: TRINO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-client-secrets
                key: trino
        command:
          - bash
          - -x
          - -euo
          - pipefail
          - -c
          - |
            echo "Download keycloak"
            curl -LO https://github.com/keycloak/keycloak/releases/download/22.0.3/keycloak-22.0.3.zip
            unzip keycloak-22.0.3.zip
            cd keycloak-22.0.3/bin
            ./kcadm.sh config credentials --config kcadm.conf --server http://key-server:8080/ --realm master --user admin --password "$KEYCLOAK_ADMIN_PASSWORD"
            ./kcadm.sh create clients -r gaia-x --config kcadm.conf -f - << EOF || true
            {
              "clientId": "trino",
              "enabled": true,
              "clientAuthenticatorType": "client-secret",
              "secret": "$TRINO_CLIENT_SECRET",
              "redirectUris": [
                "*"
              ],
              "webOrigins": [
                "*"
              ],
              "standardFlowEnabled": true,
              "protocol": "openid-connect"
            }
            EOF
            ./kcadm.sh create clients -r gaia-x --config kcadm.conf -f - << EOF || true
            {
              "clientId": "superset",
              "enabled": true,
              "clientAuthenticatorType": "client-secret",
              "secret": "$SUPERSET_CLIENT_SECRET",
              "redirectUris": [
                "*"
              ],
              "webOrigins": [
                "*"
              ],
              "standardFlowEnabled": true,
              "protocol": "openid-connect"
            }
            EOF
      serviceAccountName: demo-serviceaccount
      restartPolicy: OnFailure
  backoffLimit: 20 # give some time for the Keycloak to be available
