---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: uc2-superset
spec:
  provider:
    oidc:
      hostname: kc.ssi.stackable.tech
      rootPath: /realms/test
      principalClaim: preferred_username
      scopes:
      - openid
      - profile
      tls:
        verification:
          server:
            caCert:
              webPki: {}
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 4.0.2
  clusterConfig:
    listenerClass: external-unstable
    authentication:
      - authenticationClass: uc2-superset
        oidc:
          clientCredentialsSecret: kc-superset-oidc-config
    credentialsSecret: superset-credentials
    mapboxSecret: superset-mapbox-api-key
  nodes:
    roleGroups:
      default:
        replicas: 1
    configOverrides:
      superset_config.py:
        # MAPBOX
        ROW_LIMIT: "200000"
        SQL_MAX_ROW: "200000"
        # OIDC
        AUTH_TYPE: "AUTH_OID"
        OIDC_CLIENT_SECRETS: '"oidc/client_config.json"'
        OIDC_ID_TOKEN_COOKIE_SECURE: '"false"'
        OIDC_OPENID_REALM: '"test"'
        OIDC_INTROSPECTION_AUTH_METHOD: '"client_secret_post"'
        AUTH_USER_REGISTRATION: 'true'
        EXPERIMENTAL_FILE_FOOTER: |
          from flask_appbuilder.security.manager import AUTH_OID
          from superset.security import SupersetSecurityManager
          from flask_oidc import OpenIDConnect
          from flask_appbuilder.security.views import AuthOIDView
          from flask_login import login_user
          from urllib.parse import quote
          from flask_appbuilder.views import expose
          from flask import (
              redirect,
              request,
              session
          )
          import logging
          import urllib
          import json
          
          AUTH_ROLES_MAPPING = {
            'default-roles-test': 'Admin',
          }

          # if we should replace ALL the user's roles each login, or only on registration
          AUTH_ROLES_SYNC_AT_LOGIN = False

          # The default user self registration role
          AUTH_USER_REGISTRATION_ROLE = "default-roles-test"


          class CustomOIDCSecurityManager(SupersetSecurityManager):
              def __init__(self, appbuilder):
                  super(CustomOIDCSecurityManager, self).__init__(appbuilder)
                  if self.auth_type == AUTH_OID:
                      self.oid = OpenIDConnect(self.appbuilder.get_app)
                  self.authoidview = AuthOIDCView

          class AuthOIDCView(AuthOIDView):
              @expose('/login/', methods=['GET', 'POST'])
              def login(self, flag=True):
                  sm = self.appbuilder.sm
                  oidc = sm.oid

                  def update_user_roles(user):
                    logging.debug(f'Old User Roles: {user.roles}')

                    # Updating user roles
                    new_roles = [sm.find_role(role) for role in map_roles()]
                    user.roles = new_roles
                    sm.update_user(user)

                    logging.debug(f'Updated user: {user} with roles {user.roles}')

                  def map_roles() -> list:
                    roles = list()

                    for role in AUTH_ROLES_MAPPING:
                      for group in ( group for group in oidc.user_getfield('groups') if role == group):
                        roles.append(AUTH_ROLES_MAPPING[role])

                    if not roles:
                      roles.append(AUTH_ROLES_MAPPING['default-roles-test']) 
                    logging.debug(f'found roles: {roles}')
                    return roles

                  @self.appbuilder.sm.oid.require_login
                  def handle_login():
                      
                      info = oidc.user_getinfo(['preferred_username', 'email', 'groups'])
                      email = f"{info.get('preferred_username')}@marispacex.com"
                      user = sm.auth_user_oid(email)

                      logging.info(f"Found user: {user} with {oidc.user_getfield('preferred_username')}")

                      # None will be returned if it is the users first time login into superset using keycloak.
                      if user is None:
                          #info = oidc.user_getinfo(['preferred_username', 'email', 'groups'])
                          logging.info(info)
                          user = sm.add_user(info.get('preferred_username'), "Marispace-X", "Participant",
                                            f"{info.get('preferred_username')}@marispacex.com", sm.find_role('Admin'))
                       # [sm.find_role(role) for role in map_roles()])
                      else:
                        # If automatic role updates enabled, update at login
                        if AUTH_ROLES_SYNC_AT_LOGIN: 
                          update_user_roles(user)
                      
                      login_user(user, remember=False)
                      logging.debug(f'Logged in {user}')
                      return redirect(self.appbuilder.get_url_for_index)

                  return handle_login()

              @expose('/logout/', methods=['GET', 'POST'])
              def logout(self):
                  oidc = self.appbuilder.sm.oid

                  oidc.logout()
                  super(AuthOIDCView, self).logout()
                  redirect_url = request.url_root + "logout"

                  return redirect(
                      # This works with Keycloak > 18 as there was a breaking change in `redirect_uri`
                      oidc.client_secrets.get('issuer') + '/protocol/openid-connect/logout?post_logout_redirect_uri=' + quote(redirect_url) + '&id_token_hint=' + session.get('oidc_auth_token').get('id_token') )

                # Actually use the custom security managed
          CUSTOM_SECURITY_MANAGER = CustomOIDCSecurityManager
    podOverrides:
      spec:
        containers:
          - name: superset
            volumeMounts:
              - mountPath: /stackable/oidc
                name: kc-superset-oidc-config
        volumes:
          - name: kc-superset-oidc-config
            secret:
              secretName: kc-superset-oidc-config
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: adminadmin
  connections.secretKey: supersetSecretKey
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@postgresql-superset/superset
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-mapbox-api-key
type: Opaque
stringData:
  connections.mapboxApiKey: "pk.eyJ1IjoibXVlbGxlcmNlbGluZSIsImEiOiJjbDZwM3llMTAwNGpmM2psdHU0Y21wZHJwIn0.kXFJKBbeyhbwf0z460JcTQ"
