---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: uc2-superset
spec:
  provider:
    oidc:
      hostname: kc.ssi.stackable.tech
      rootPath: /realms/test
      principalClaim: preferred_username
      scopes:
      - openid
      - profile
      tls:
        verification:
          server:
            caCert:
              webPki: {}
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 4.0.2
  clusterConfig:
    listenerClass: external-unstable
    authentication:
      - authenticationClass: uc2-superset
        oidc:
          clientCredentialsSecret: kc-superset-oidc-config
    credentialsSecret: superset-credentials
    mapboxSecret: superset-mapbox-api-key
  nodes:
    roleGroups:
      default:
        replicas: 1
    configOverrides:
      superset_config.py:
        # MAPBOX
        ROW_LIMIT: "200000"
        SQL_MAX_ROW: "200000"
        # OIDC
        AUTH_TYPE: "AUTH_OAUTH"
        OIDC_CLIENT_SECRETS: '"oidc/client_config.json"'
        OIDC_ID_TOKEN_COOKIE_SECURE: '"false"'
        OIDC_OPENID_REALM: '"test"'
        OIDC_INTROSPECTION_AUTH_METHOD: '"client_secret_post"'
        AUTH_USER_REGISTRATION: 'true'
    podOverrides:
      spec:
        containers:
          - name: superset
            volumeMounts:
              - mountPath: /stackable/oidc
                name: kc-superset-oidc-config
        volumes:
          - name: kc-superset-oidc-config
            secret:
              secretName: kc-superset-oidc-config
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: adminadmin
  connections.secretKey: supersetSecretKey
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@postgresql-superset/superset
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-mapbox-api-key
type: Opaque
stringData:
  connections.mapboxApiKey: "pk.eyJ1IjoibXVlbGxlcmNlbGluZSIsImEiOiJjbDZwM3llMTAwNGpmM2psdHU0Y21wZHJwIn0.kXFJKBbeyhbwf0z460JcTQ"
